/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


/// <summary>
/// The Fraction Cells for results on Fraction of scan
/// </summary>
public partial class FCells : TBase
{
  private Dictionary<byte[], FCells> _f;
  private List<FCell> _cells;
  private List<FCellSerial> _serial_cells;

  /// <summary>
  /// The Fraction Container for the Next Fractions Tree,  defined as FCells items in a map-container by current Fraction bytes
  /// </summary>
  public Dictionary<byte[], FCells> F
  {
    get
    {
      return _f;
    }
    set
    {
      __isset.f = true;
      this._f = value;
    }
  }

  /// <summary>
  /// The current Fraction's Cells, defined as FCell items in a list-container
  /// </summary>
  public List<FCell> Cells
  {
    get
    {
      return _cells;
    }
    set
    {
      __isset.cells = true;
      this._cells = value;
    }
  }

  /// <summary>
  /// The current Fraction's Serial Cells, defined as FCellSerial items in a list-container
  /// </summary>
  public List<FCellSerial> Serial_cells
  {
    get
    {
      return _serial_cells;
    }
    set
    {
      __isset.serial_cells = true;
      this._serial_cells = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool f;
    public bool cells;
    public bool serial_cells;
  }

  public FCells()
  {
  }

  public FCells DeepCopy()
  {
    var tmp457 = new FCells();
    if((F != null) && __isset.f)
    {
      tmp457.F = this.F.DeepCopy();
    }
    tmp457.__isset.f = this.__isset.f;
    if((Cells != null) && __isset.cells)
    {
      tmp457.Cells = this.Cells.DeepCopy();
    }
    tmp457.__isset.cells = this.__isset.cells;
    if((Serial_cells != null) && __isset.serial_cells)
    {
      tmp457.Serial_cells = this.Serial_cells.DeepCopy();
    }
    tmp457.__isset.serial_cells = this.__isset.serial_cells;
    return tmp457;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map)
            {
              {
                var _map458 = await iprot.ReadMapBeginAsync(cancellationToken);
                F = new Dictionary<byte[], FCells>(_map458.Count);
                for(int _i459 = 0; _i459 < _map458.Count; ++_i459)
                {
                  byte[] _key460;
                  FCells _val461;
                  _key460 = await iprot.ReadBinaryAsync(cancellationToken);
                  _val461 = new FCells();
                  await _val461.ReadAsync(iprot, cancellationToken);
                  F[_key460] = _val461;
                }
                await iprot.ReadMapEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.List)
            {
              {
                var _list462 = await iprot.ReadListBeginAsync(cancellationToken);
                Cells = new List<FCell>(_list462.Count);
                for(int _i463 = 0; _i463 < _list462.Count; ++_i463)
                {
                  FCell _elem464;
                  _elem464 = new FCell();
                  await _elem464.ReadAsync(iprot, cancellationToken);
                  Cells.Add(_elem464);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.List)
            {
              {
                var _list465 = await iprot.ReadListBeginAsync(cancellationToken);
                Serial_cells = new List<FCellSerial>(_list465.Count);
                for(int _i466 = 0; _i466 < _list465.Count; ++_i466)
                {
                  FCellSerial _elem467;
                  _elem467 = new FCellSerial();
                  await _elem467.ReadAsync(iprot, cancellationToken);
                  Serial_cells.Add(_elem467);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp468 = new TStruct("FCells");
      await oprot.WriteStructBeginAsync(tmp468, cancellationToken);
      var tmp469 = new TField();
      if((F != null) && __isset.f)
      {
        tmp469.Name = "f";
        tmp469.Type = TType.Map;
        tmp469.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp469, cancellationToken);
        await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, F.Count), cancellationToken);
        foreach (byte[] _iter470 in F.Keys)
        {
          await oprot.WriteBinaryAsync(_iter470, cancellationToken);
          await F[_iter470].WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMapEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Cells != null) && __isset.cells)
      {
        tmp469.Name = "cells";
        tmp469.Type = TType.List;
        tmp469.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp469, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.Struct, Cells.Count), cancellationToken);
        foreach (FCell _iter471 in Cells)
        {
          await _iter471.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Serial_cells != null) && __isset.serial_cells)
      {
        tmp469.Name = "serial_cells";
        tmp469.Type = TType.List;
        tmp469.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp469, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.Struct, Serial_cells.Count), cancellationToken);
        foreach (FCellSerial _iter472 in Serial_cells)
        {
          await _iter472.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is FCells other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.f == other.__isset.f) && ((!__isset.f) || (TCollections.Equals(F, other.F))))
      && ((__isset.cells == other.__isset.cells) && ((!__isset.cells) || (TCollections.Equals(Cells, other.Cells))))
      && ((__isset.serial_cells == other.__isset.serial_cells) && ((!__isset.serial_cells) || (TCollections.Equals(Serial_cells, other.Serial_cells))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((F != null) && __isset.f)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(F);
      }
      if((Cells != null) && __isset.cells)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Cells);
      }
      if((Serial_cells != null) && __isset.serial_cells)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Serial_cells);
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp473 = new StringBuilder("FCells(");
    int tmp474 = 0;
    if((F != null) && __isset.f)
    {
      if(0 < tmp474++) { tmp473.Append(", "); }
      tmp473.Append("F: ");
      F.ToString(tmp473);
    }
    if((Cells != null) && __isset.cells)
    {
      if(0 < tmp474++) { tmp473.Append(", "); }
      tmp473.Append("Cells: ");
      Cells.ToString(tmp473);
    }
    if((Serial_cells != null) && __isset.serial_cells)
    {
      if(0 < tmp474++) { tmp473.Append(", "); }
      tmp473.Append("Serial_cells: ");
      Serial_cells.ToString(tmp473);
    }
    tmp473.Append(')');
    return tmp473.ToString();
  }
}

