/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */

#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

/// <summary>
/// The Cell Flag
/// </summary>
public enum Flag
{
  /// <summary>
  /// Unknown/Undefined
  /// </summary>
  NONE = 0,
  /// <summary>
  /// The Cell is an insert
  /// </summary>
  INSERT = 1,
  /// <summary>
  /// The Cell is a delete versions lower-equal
  /// </summary>
  DELETE_LE = 2,
  /// <summary>
  /// The Cell is a  delete version equal
  /// </summary>
  DELETE_EQ = 3,
}
