/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */

#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

/// <summary>
/// Manage Columns schema function Flags
/// </summary>
public enum SchemaFunc
{
  /// <summary>
  /// Create Column Function
  /// </summary>
  CREATE = 3,
  /// <summary>
  /// Delete Column Function
  /// </summary>
  REMOVE = 5,
  /// <summary>
  /// Modify Column Function
  /// </summary>
  MODIFY = 7,
}
