/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


/// <summary>
/// The Scan Specifications, the Columns-Intervals(SpecColumn/s) with global-scope Flags
/// </summary>
public partial class SpecScan : TBase
{
  private List<SpecColumn> _columns;
  private List<SpecColumnSerial> _columns_serial;
  private SpecFlags _flags;

  /// <summary>
  /// The Column Intervals(SpecColumn) in a list-container
  /// </summary>
  public List<SpecColumn> Columns
  {
    get
    {
      return _columns;
    }
    set
    {
      __isset.columns = true;
      this._columns = value;
    }
  }

  /// <summary>
  /// The Serial Column Intervals(SpecColumnSerial) in a list-container
  /// </summary>
  public List<SpecColumnSerial> Columns_serial
  {
    get
    {
      return _columns_serial;
    }
    set
    {
      __isset.columns_serial = true;
      this._columns_serial = value;
    }
  }

  /// <summary>
  /// The Global Flags Specification
  /// </summary>
  public SpecFlags Flags
  {
    get
    {
      return _flags;
    }
    set
    {
      __isset.flags = true;
      this._flags = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool columns;
    public bool columns_serial;
    public bool flags;
  }

  public SpecScan()
  {
  }

  public SpecScan DeepCopy()
  {
    var tmp221 = new SpecScan();
    if((Columns != null) && __isset.columns)
    {
      tmp221.Columns = this.Columns.DeepCopy();
    }
    tmp221.__isset.columns = this.__isset.columns;
    if((Columns_serial != null) && __isset.columns_serial)
    {
      tmp221.Columns_serial = this.Columns_serial.DeepCopy();
    }
    tmp221.__isset.columns_serial = this.__isset.columns_serial;
    if((Flags != null) && __isset.flags)
    {
      tmp221.Flags = (SpecFlags)this.Flags.DeepCopy();
    }
    tmp221.__isset.flags = this.__isset.flags;
    return tmp221;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List)
            {
              {
                TList _list222 = await iprot.ReadListBeginAsync(cancellationToken);
                Columns = new List<SpecColumn>(_list222.Count);
                for(int _i223 = 0; _i223 < _list222.Count; ++_i223)
                {
                  SpecColumn _elem224;
                  _elem224 = new SpecColumn();
                  await _elem224.ReadAsync(iprot, cancellationToken);
                  Columns.Add(_elem224);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.List)
            {
              {
                TList _list225 = await iprot.ReadListBeginAsync(cancellationToken);
                Columns_serial = new List<SpecColumnSerial>(_list225.Count);
                for(int _i226 = 0; _i226 < _list225.Count; ++_i226)
                {
                  SpecColumnSerial _elem227;
                  _elem227 = new SpecColumnSerial();
                  await _elem227.ReadAsync(iprot, cancellationToken);
                  Columns_serial.Add(_elem227);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.Struct)
            {
              Flags = new SpecFlags();
              await Flags.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp228 = new TStruct("SpecScan");
      await oprot.WriteStructBeginAsync(tmp228, cancellationToken);
      var tmp229 = new TField();
      if((Columns != null) && __isset.columns)
      {
        tmp229.Name = "columns";
        tmp229.Type = TType.List;
        tmp229.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp229, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Columns.Count), cancellationToken);
          foreach (SpecColumn _iter230 in Columns)
          {
            await _iter230.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Columns_serial != null) && __isset.columns_serial)
      {
        tmp229.Name = "columns_serial";
        tmp229.Type = TType.List;
        tmp229.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp229, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Columns_serial.Count), cancellationToken);
          foreach (SpecColumnSerial _iter231 in Columns_serial)
          {
            await _iter231.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Flags != null) && __isset.flags)
      {
        tmp229.Name = "flags";
        tmp229.Type = TType.Struct;
        tmp229.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp229, cancellationToken);
        await Flags.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is SpecScan other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.columns == other.__isset.columns) && ((!__isset.columns) || (TCollections.Equals(Columns, other.Columns))))
      && ((__isset.columns_serial == other.__isset.columns_serial) && ((!__isset.columns_serial) || (TCollections.Equals(Columns_serial, other.Columns_serial))))
      && ((__isset.flags == other.__isset.flags) && ((!__isset.flags) || (global::System.Object.Equals(Flags, other.Flags))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((Columns != null) && __isset.columns)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Columns);
      }
      if((Columns_serial != null) && __isset.columns_serial)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Columns_serial);
      }
      if((Flags != null) && __isset.flags)
      {
        hashcode = (hashcode * 397) + Flags.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp232 = new StringBuilder("SpecScan(");
    int tmp233 = 0;
    if((Columns != null) && __isset.columns)
    {
      if(0 < tmp233++) { tmp232.Append(", "); }
      tmp232.Append("Columns: ");
      Columns.ToString(tmp232);
    }
    if((Columns_serial != null) && __isset.columns_serial)
    {
      if(0 < tmp233++) { tmp232.Append(", "); }
      tmp232.Append("Columns_serial: ");
      Columns_serial.ToString(tmp232);
    }
    if((Flags != null) && __isset.flags)
    {
      if(0 < tmp233++) { tmp232.Append(", "); }
      tmp232.Append("Flags: ");
      Flags.ToString(tmp232);
    }
    tmp232.Append(')');
    return tmp232.ToString();
  }
}

