/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



public partial class FCells : TBase
{
  private Dictionary<byte[], FCells> _f;
  private List<FCell> _cells;

  public Dictionary<byte[], FCells> F
  {
    get
    {
      return _f;
    }
    set
    {
      __isset.f = true;
      this._f = value;
    }
  }

  public List<FCell> Cells
  {
    get
    {
      return _cells;
    }
    set
    {
      __isset.cells = true;
      this._cells = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool f;
    public bool cells;
  }

  public FCells()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map)
            {
              {
                TMap _map64 = await iprot.ReadMapBeginAsync(cancellationToken);
                F = new Dictionary<byte[], FCells>(_map64.Count);
                for(int _i65 = 0; _i65 < _map64.Count; ++_i65)
                {
                  byte[] _key66;
                  FCells _val67;
                  _key66 = await iprot.ReadBinaryAsync(cancellationToken);
                  _val67 = new FCells();
                  await _val67.ReadAsync(iprot, cancellationToken);
                  F[_key66] = _val67;
                }
                await iprot.ReadMapEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.List)
            {
              {
                TList _list68 = await iprot.ReadListBeginAsync(cancellationToken);
                Cells = new List<FCell>(_list68.Count);
                for(int _i69 = 0; _i69 < _list68.Count; ++_i69)
                {
                  FCell _elem70;
                  _elem70 = new FCell();
                  await _elem70.ReadAsync(iprot, cancellationToken);
                  Cells.Add(_elem70);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("FCells");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (F != null && __isset.f)
      {
        field.Name = "f";
        field.Type = TType.Map;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, F.Count), cancellationToken);
          foreach (byte[] _iter71 in F.Keys)
          {
            await oprot.WriteBinaryAsync(_iter71, cancellationToken);
            await F[_iter71].WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (Cells != null && __isset.cells)
      {
        field.Name = "cells";
        field.Type = TType.List;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Cells.Count), cancellationToken);
          foreach (FCell _iter72 in Cells)
          {
            await _iter72.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as FCells;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.f == other.__isset.f) && ((!__isset.f) || (TCollections.Equals(F, other.F))))
      && ((__isset.cells == other.__isset.cells) && ((!__isset.cells) || (TCollections.Equals(Cells, other.Cells))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.f)
        hashcode = (hashcode * 397) + TCollections.GetHashCode(F);
      if(__isset.cells)
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Cells);
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("FCells(");
    bool __first = true;
    if (F != null && __isset.f)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("F: ");
      sb.Append(F);
    }
    if (Cells != null && __isset.cells)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Cells: ");
      sb.Append(Cells);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

