/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling


/// <summary>
/// A Grouped Cells result for results of scan, determined by the request's CellsResult enum
/// </summary>
public partial class CellsGroup : TBase
{
  private Cells _cells;
  private Dictionary<string, ColCells> _ccells;
  private List<kCells> _kcells;
  private FCells _fcells;

  /// <summary>
  /// The Cells in a list, defined as Cell items in a list-container
  /// </summary>
  public Cells Cells
  {
    get
    {
      return _cells;
    }
    set
    {
      __isset.cells = true;
      this._cells = value;
    }
  }

  /// <summary>
  /// The Columns Cells in a map-container, defined as ColCells items by Column Name
  /// </summary>
  public Dictionary<string, ColCells> Ccells
  {
    get
    {
      return _ccells;
    }
    set
    {
      __isset.ccells = true;
      this._ccells = value;
    }
  }

  /// <summary>
  /// The Keys Cells in a list, defined as kCells items in a list-container
  /// </summary>
  public List<kCells> Kcells
  {
    get
    {
      return _kcells;
    }
    set
    {
      __isset.kcells = true;
      this._kcells = value;
    }
  }

  /// <summary>
  /// The Fraction Cells in struct FCells
  /// </summary>
  public FCells Fcells
  {
    get
    {
      return _fcells;
    }
    set
    {
      __isset.fcells = true;
      this._fcells = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool cells;
    public bool ccells;
    public bool kcells;
    public bool fcells;
  }

  public CellsGroup()
  {
  }

  public CellsGroup DeepCopy()
  {
    var tmp263 = new CellsGroup();
    if((Cells != null) && __isset.cells)
    {
      tmp263.Cells = (Cells)this.Cells.DeepCopy();
    }
    tmp263.__isset.cells = this.__isset.cells;
    if((Ccells != null) && __isset.ccells)
    {
      tmp263.Ccells = this.Ccells.DeepCopy();
    }
    tmp263.__isset.ccells = this.__isset.ccells;
    if((Kcells != null) && __isset.kcells)
    {
      tmp263.Kcells = this.Kcells.DeepCopy();
    }
    tmp263.__isset.kcells = this.__isset.kcells;
    if((Fcells != null) && __isset.fcells)
    {
      tmp263.Fcells = (FCells)this.Fcells.DeepCopy();
    }
    tmp263.__isset.fcells = this.__isset.fcells;
    return tmp263;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              Cells = new Cells();
              await Cells.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.Map)
            {
              {
                TMap _map264 = await iprot.ReadMapBeginAsync(cancellationToken);
                Ccells = new Dictionary<string, ColCells>(_map264.Count);
                for(int _i265 = 0; _i265 < _map264.Count; ++_i265)
                {
                  string _key266;
                  ColCells _val267;
                  _key266 = await iprot.ReadStringAsync(cancellationToken);
                  _val267 = new ColCells();
                  await _val267.ReadAsync(iprot, cancellationToken);
                  Ccells[_key266] = _val267;
                }
                await iprot.ReadMapEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.List)
            {
              {
                TList _list268 = await iprot.ReadListBeginAsync(cancellationToken);
                Kcells = new List<kCells>(_list268.Count);
                for(int _i269 = 0; _i269 < _list268.Count; ++_i269)
                {
                  kCells _elem270;
                  _elem270 = new kCells();
                  await _elem270.ReadAsync(iprot, cancellationToken);
                  Kcells.Add(_elem270);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.Struct)
            {
              Fcells = new FCells();
              await Fcells.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("CellsGroup");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if((Cells != null) && __isset.cells)
      {
        field.Name = "cells";
        field.Type = TType.Struct;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Cells.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Ccells != null) && __isset.ccells)
      {
        field.Name = "ccells";
        field.Type = TType.Map;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, Ccells.Count), cancellationToken);
          foreach (string _iter271 in Ccells.Keys)
          {
            await oprot.WriteStringAsync(_iter271, cancellationToken);
            await Ccells[_iter271].WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Kcells != null) && __isset.kcells)
      {
        field.Name = "kcells";
        field.Type = TType.List;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Kcells.Count), cancellationToken);
          foreach (kCells _iter272 in Kcells)
          {
            await _iter272.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Fcells != null) && __isset.fcells)
      {
        field.Name = "fcells";
        field.Type = TType.Struct;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Fcells.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is CellsGroup other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.cells == other.__isset.cells) && ((!__isset.cells) || (System.Object.Equals(Cells, other.Cells))))
      && ((__isset.ccells == other.__isset.ccells) && ((!__isset.ccells) || (System.Object.Equals(Ccells, other.Ccells))))
      && ((__isset.kcells == other.__isset.kcells) && ((!__isset.kcells) || (System.Object.Equals(Kcells, other.Kcells))))
      && ((__isset.fcells == other.__isset.fcells) && ((!__isset.fcells) || (System.Object.Equals(Fcells, other.Fcells))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((Cells != null) && __isset.cells)
      {
        hashcode = (hashcode * 397) + Cells.GetHashCode();
      }
      if((Ccells != null) && __isset.ccells)
      {
        hashcode = (hashcode * 397) + Ccells.GetHashCode();
      }
      if((Kcells != null) && __isset.kcells)
      {
        hashcode = (hashcode * 397) + Kcells.GetHashCode();
      }
      if((Fcells != null) && __isset.fcells)
      {
        hashcode = (hashcode * 397) + Fcells.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("CellsGroup(");
    int tmp273 = 0;
    if((Cells != null) && __isset.cells)
    {
      if(0 < tmp273++) { sb.Append(", "); }
      sb.Append("Cells: ");
      Cells.ToString(sb);
    }
    if((Ccells != null) && __isset.ccells)
    {
      if(0 < tmp273++) { sb.Append(", "); }
      sb.Append("Ccells: ");
      Ccells.ToString(sb);
    }
    if((Kcells != null) && __isset.kcells)
    {
      if(0 < tmp273++) { sb.Append(", "); }
      sb.Append("Kcells: ");
      Kcells.ToString(sb);
    }
    if((Fcells != null) && __isset.fcells)
    {
      if(0 < tmp273++) { sb.Append(", "); }
      sb.Append("Fcells: ");
      Fcells.ToString(sb);
    }
    sb.Append(')');
    return sb.ToString();
  }
}

