/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling


/// <summary>
/// The Cells Interval Specifications with interval-scope Flags
/// </summary>
public partial class SpecInterval : TBase
{
  private List<byte[]> _range_begin;
  private List<byte[]> _range_end;
  private List<byte[]> _offset_key;
  private long _offset_rev;
  private List<SpecKeyInterval> _key_intervals;
  private List<SpecValue> _values;
  private SpecTimestamp _ts_start;
  private SpecTimestamp _ts_finish;
  private SpecFlags _flags;

  /// <summary>
  /// Begin of Ranges evaluation with this Key inclusive
  /// </summary>
  public List<byte[]> Range_begin
  {
    get
    {
      return _range_begin;
    }
    set
    {
      __isset.range_begin = true;
      this._range_begin = value;
    }
  }

  /// <summary>
  /// End of Ranges evaluation with this Key inclusive
  /// </summary>
  public List<byte[]> Range_end
  {
    get
    {
      return _range_end;
    }
    set
    {
      __isset.range_end = true;
      this._range_end = value;
    }
  }

  /// <summary>
  /// Offset Cell Key of a Scan, select cells from this key inclusive
  /// </summary>
  public List<byte[]> Offset_key
  {
    get
    {
      return _offset_key;
    }
    set
    {
      __isset.offset_key = true;
      this._offset_key = value;
    }
  }

  /// <summary>
  /// Offset Cell Timestamp of a Scan, select cells after this timestamp
  /// </summary>
  public long Offset_rev
  {
    get
    {
      return _offset_rev;
    }
    set
    {
      __isset.offset_rev = true;
      this._offset_rev = value;
    }
  }

  /// <summary>
  /// The Key Intervals
  /// </summary>
  public List<SpecKeyInterval> Key_intervals
  {
    get
    {
      return _key_intervals;
    }
    set
    {
      __isset.key_intervals = true;
      this._key_intervals = value;
    }
  }

  /// <summary>
  /// The Cell Value Specifications, cell-value match
  /// </summary>
  public List<SpecValue> Values
  {
    get
    {
      return _values;
    }
    set
    {
      __isset.values = true;
      this._values = value;
    }
  }

  /// <summary>
  /// The Timestamp Start Spec, the start of cells-interval timestamp match
  /// </summary>
  public SpecTimestamp Ts_start
  {
    get
    {
      return _ts_start;
    }
    set
    {
      __isset.ts_start = true;
      this._ts_start = value;
    }
  }

  /// <summary>
  /// The Timestamp Finish Spec, the finish of cells-interval timestamp match
  /// </summary>
  public SpecTimestamp Ts_finish
  {
    get
    {
      return _ts_finish;
    }
    set
    {
      __isset.ts_finish = true;
      this._ts_finish = value;
    }
  }

  /// <summary>
  /// The Interval Flags Specification
  /// </summary>
  public SpecFlags Flags
  {
    get
    {
      return _flags;
    }
    set
    {
      __isset.flags = true;
      this._flags = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool range_begin;
    public bool range_end;
    public bool offset_key;
    public bool offset_rev;
    public bool key_intervals;
    public bool values;
    public bool ts_start;
    public bool ts_finish;
    public bool flags;
  }

  public SpecInterval()
  {
  }

  public SpecInterval DeepCopy()
  {
    var tmp50 = new SpecInterval();
    if((Range_begin != null) && __isset.range_begin)
    {
      tmp50.Range_begin = this.Range_begin.DeepCopy();
    }
    tmp50.__isset.range_begin = this.__isset.range_begin;
    if((Range_end != null) && __isset.range_end)
    {
      tmp50.Range_end = this.Range_end.DeepCopy();
    }
    tmp50.__isset.range_end = this.__isset.range_end;
    if((Offset_key != null) && __isset.offset_key)
    {
      tmp50.Offset_key = this.Offset_key.DeepCopy();
    }
    tmp50.__isset.offset_key = this.__isset.offset_key;
    if(__isset.offset_rev)
    {
      tmp50.Offset_rev = this.Offset_rev;
    }
    tmp50.__isset.offset_rev = this.__isset.offset_rev;
    if((Key_intervals != null) && __isset.key_intervals)
    {
      tmp50.Key_intervals = this.Key_intervals.DeepCopy();
    }
    tmp50.__isset.key_intervals = this.__isset.key_intervals;
    if((Values != null) && __isset.values)
    {
      tmp50.Values = this.Values.DeepCopy();
    }
    tmp50.__isset.values = this.__isset.values;
    if((Ts_start != null) && __isset.ts_start)
    {
      tmp50.Ts_start = (SpecTimestamp)this.Ts_start.DeepCopy();
    }
    tmp50.__isset.ts_start = this.__isset.ts_start;
    if((Ts_finish != null) && __isset.ts_finish)
    {
      tmp50.Ts_finish = (SpecTimestamp)this.Ts_finish.DeepCopy();
    }
    tmp50.__isset.ts_finish = this.__isset.ts_finish;
    if((Flags != null) && __isset.flags)
    {
      tmp50.Flags = (SpecFlags)this.Flags.DeepCopy();
    }
    tmp50.__isset.flags = this.__isset.flags;
    return tmp50;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List)
            {
              {
                TList _list51 = await iprot.ReadListBeginAsync(cancellationToken);
                Range_begin = new List<byte[]>(_list51.Count);
                for(int _i52 = 0; _i52 < _list51.Count; ++_i52)
                {
                  byte[] _elem53;
                  _elem53 = await iprot.ReadBinaryAsync(cancellationToken);
                  Range_begin.Add(_elem53);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.List)
            {
              {
                TList _list54 = await iprot.ReadListBeginAsync(cancellationToken);
                Range_end = new List<byte[]>(_list54.Count);
                for(int _i55 = 0; _i55 < _list54.Count; ++_i55)
                {
                  byte[] _elem56;
                  _elem56 = await iprot.ReadBinaryAsync(cancellationToken);
                  Range_end.Add(_elem56);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.List)
            {
              {
                TList _list57 = await iprot.ReadListBeginAsync(cancellationToken);
                Offset_key = new List<byte[]>(_list57.Count);
                for(int _i58 = 0; _i58 < _list57.Count; ++_i58)
                {
                  byte[] _elem59;
                  _elem59 = await iprot.ReadBinaryAsync(cancellationToken);
                  Offset_key.Add(_elem59);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.I64)
            {
              Offset_rev = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.List)
            {
              {
                TList _list60 = await iprot.ReadListBeginAsync(cancellationToken);
                Key_intervals = new List<SpecKeyInterval>(_list60.Count);
                for(int _i61 = 0; _i61 < _list60.Count; ++_i61)
                {
                  SpecKeyInterval _elem62;
                  _elem62 = new SpecKeyInterval();
                  await _elem62.ReadAsync(iprot, cancellationToken);
                  Key_intervals.Add(_elem62);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.List)
            {
              {
                TList _list63 = await iprot.ReadListBeginAsync(cancellationToken);
                Values = new List<SpecValue>(_list63.Count);
                for(int _i64 = 0; _i64 < _list63.Count; ++_i64)
                {
                  SpecValue _elem65;
                  _elem65 = new SpecValue();
                  await _elem65.ReadAsync(iprot, cancellationToken);
                  Values.Add(_elem65);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.Struct)
            {
              Ts_start = new SpecTimestamp();
              await Ts_start.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.Struct)
            {
              Ts_finish = new SpecTimestamp();
              await Ts_finish.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.Struct)
            {
              Flags = new SpecFlags();
              await Flags.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("SpecInterval");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if((Range_begin != null) && __isset.range_begin)
      {
        field.Name = "range_begin";
        field.Type = TType.List;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, Range_begin.Count), cancellationToken);
          foreach (byte[] _iter66 in Range_begin)
          {
            await oprot.WriteBinaryAsync(_iter66, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Range_end != null) && __isset.range_end)
      {
        field.Name = "range_end";
        field.Type = TType.List;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, Range_end.Count), cancellationToken);
          foreach (byte[] _iter67 in Range_end)
          {
            await oprot.WriteBinaryAsync(_iter67, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Offset_key != null) && __isset.offset_key)
      {
        field.Name = "offset_key";
        field.Type = TType.List;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, Offset_key.Count), cancellationToken);
          foreach (byte[] _iter68 in Offset_key)
          {
            await oprot.WriteBinaryAsync(_iter68, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.offset_rev)
      {
        field.Name = "offset_rev";
        field.Type = TType.I64;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI64Async(Offset_rev, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Key_intervals != null) && __isset.key_intervals)
      {
        field.Name = "key_intervals";
        field.Type = TType.List;
        field.ID = 5;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Key_intervals.Count), cancellationToken);
          foreach (SpecKeyInterval _iter69 in Key_intervals)
          {
            await _iter69.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Values != null) && __isset.values)
      {
        field.Name = "values";
        field.Type = TType.List;
        field.ID = 6;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Values.Count), cancellationToken);
          foreach (SpecValue _iter70 in Values)
          {
            await _iter70.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Ts_start != null) && __isset.ts_start)
      {
        field.Name = "ts_start";
        field.Type = TType.Struct;
        field.ID = 7;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Ts_start.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Ts_finish != null) && __isset.ts_finish)
      {
        field.Name = "ts_finish";
        field.Type = TType.Struct;
        field.ID = 8;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Ts_finish.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Flags != null) && __isset.flags)
      {
        field.Name = "flags";
        field.Type = TType.Struct;
        field.ID = 9;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Flags.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is SpecInterval other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.range_begin == other.__isset.range_begin) && ((!__isset.range_begin) || (System.Object.Equals(Range_begin, other.Range_begin))))
      && ((__isset.range_end == other.__isset.range_end) && ((!__isset.range_end) || (System.Object.Equals(Range_end, other.Range_end))))
      && ((__isset.offset_key == other.__isset.offset_key) && ((!__isset.offset_key) || (System.Object.Equals(Offset_key, other.Offset_key))))
      && ((__isset.offset_rev == other.__isset.offset_rev) && ((!__isset.offset_rev) || (System.Object.Equals(Offset_rev, other.Offset_rev))))
      && ((__isset.key_intervals == other.__isset.key_intervals) && ((!__isset.key_intervals) || (System.Object.Equals(Key_intervals, other.Key_intervals))))
      && ((__isset.values == other.__isset.values) && ((!__isset.values) || (System.Object.Equals(Values, other.Values))))
      && ((__isset.ts_start == other.__isset.ts_start) && ((!__isset.ts_start) || (System.Object.Equals(Ts_start, other.Ts_start))))
      && ((__isset.ts_finish == other.__isset.ts_finish) && ((!__isset.ts_finish) || (System.Object.Equals(Ts_finish, other.Ts_finish))))
      && ((__isset.flags == other.__isset.flags) && ((!__isset.flags) || (System.Object.Equals(Flags, other.Flags))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((Range_begin != null) && __isset.range_begin)
      {
        hashcode = (hashcode * 397) + Range_begin.GetHashCode();
      }
      if((Range_end != null) && __isset.range_end)
      {
        hashcode = (hashcode * 397) + Range_end.GetHashCode();
      }
      if((Offset_key != null) && __isset.offset_key)
      {
        hashcode = (hashcode * 397) + Offset_key.GetHashCode();
      }
      if(__isset.offset_rev)
      {
        hashcode = (hashcode * 397) + Offset_rev.GetHashCode();
      }
      if((Key_intervals != null) && __isset.key_intervals)
      {
        hashcode = (hashcode * 397) + Key_intervals.GetHashCode();
      }
      if((Values != null) && __isset.values)
      {
        hashcode = (hashcode * 397) + Values.GetHashCode();
      }
      if((Ts_start != null) && __isset.ts_start)
      {
        hashcode = (hashcode * 397) + Ts_start.GetHashCode();
      }
      if((Ts_finish != null) && __isset.ts_finish)
      {
        hashcode = (hashcode * 397) + Ts_finish.GetHashCode();
      }
      if((Flags != null) && __isset.flags)
      {
        hashcode = (hashcode * 397) + Flags.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("SpecInterval(");
    int tmp71 = 0;
    if((Range_begin != null) && __isset.range_begin)
    {
      if(0 < tmp71++) { sb.Append(", "); }
      sb.Append("Range_begin: ");
      Range_begin.ToString(sb);
    }
    if((Range_end != null) && __isset.range_end)
    {
      if(0 < tmp71++) { sb.Append(", "); }
      sb.Append("Range_end: ");
      Range_end.ToString(sb);
    }
    if((Offset_key != null) && __isset.offset_key)
    {
      if(0 < tmp71++) { sb.Append(", "); }
      sb.Append("Offset_key: ");
      Offset_key.ToString(sb);
    }
    if(__isset.offset_rev)
    {
      if(0 < tmp71++) { sb.Append(", "); }
      sb.Append("Offset_rev: ");
      Offset_rev.ToString(sb);
    }
    if((Key_intervals != null) && __isset.key_intervals)
    {
      if(0 < tmp71++) { sb.Append(", "); }
      sb.Append("Key_intervals: ");
      Key_intervals.ToString(sb);
    }
    if((Values != null) && __isset.values)
    {
      if(0 < tmp71++) { sb.Append(", "); }
      sb.Append("Values: ");
      Values.ToString(sb);
    }
    if((Ts_start != null) && __isset.ts_start)
    {
      if(0 < tmp71++) { sb.Append(", "); }
      sb.Append("Ts_start: ");
      Ts_start.ToString(sb);
    }
    if((Ts_finish != null) && __isset.ts_finish)
    {
      if(0 < tmp71++) { sb.Append(", "); }
      sb.Append("Ts_finish: ");
      Ts_finish.ToString(sb);
    }
    if((Flags != null) && __isset.flags)
    {
      if(0 < tmp71++) { sb.Append(", "); }
      sb.Append("Flags: ");
      Flags.ToString(sb);
    }
    sb.Append(')');
    return sb.ToString();
  }
}

