# ./Gemfile

source "https://rubygems.org"


gem "jekyll-rtd-theme", '~> 1.1', '>= 1.1.7'


group :jekyll_plugins do
  gem "jekyll-default-layout"
  gem "jekyll-readme-index"
  gem "jekyll-github-metadata"
  gem "jekyll-titles-from-headings"
  gem "jemoji"
  gem "jekyll-avatar"
  gem "jekyll-mentions"
  gem "jekyll-remote-theme"
end
