/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


/// <summary>
/// The Serial column type Cell for results on Columns of scan
/// </summary>
public partial class CCellSerial : TBase
{
  private List<byte[]> _k;
  private long _ts;
  private List<CellValueSerial> _v;

  /// <summary>
  /// The Cell Key
  /// </summary>
  public List<byte[]> K
  {
    get
    {
      return _k;
    }
    set
    {
      __isset.@k = true;
      this._k = value;
    }
  }

  /// <summary>
  /// The Cell Timestamp
  /// </summary>
  public long Ts
  {
    get
    {
      return _ts;
    }
    set
    {
      __isset.@ts = true;
      this._ts = value;
    }
  }

  /// <summary>
  /// The Cell Serial Value
  /// </summary>
  public List<CellValueSerial> V
  {
    get
    {
      return _v;
    }
    set
    {
      __isset.@v = true;
      this._v = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool @k;
    public bool @ts;
    public bool @v;
  }

  public CCellSerial()
  {
  }

  public CCellSerial DeepCopy()
  {
    var tmp447 = new CCellSerial();
    if((K != null) && __isset.@k)
    {
      tmp447.K = this.K.DeepCopy();
    }
    tmp447.__isset.@k = this.__isset.@k;
    if(__isset.@ts)
    {
      tmp447.Ts = this.Ts;
    }
    tmp447.__isset.@ts = this.__isset.@ts;
    if((V != null) && __isset.@v)
    {
      tmp447.V = this.V.DeepCopy();
    }
    tmp447.__isset.@v = this.__isset.@v;
    return tmp447;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List)
            {
              {
                var _list448 = await iprot.ReadListBeginAsync(cancellationToken);
                K = new List<byte[]>(_list448.Count);
                for(int _i449 = 0; _i449 < _list448.Count; ++_i449)
                {
                  byte[] _elem450;
                  _elem450 = await iprot.ReadBinaryAsync(cancellationToken);
                  K.Add(_elem450);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I64)
            {
              Ts = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.List)
            {
              {
                var _list451 = await iprot.ReadListBeginAsync(cancellationToken);
                V = new List<CellValueSerial>(_list451.Count);
                for(int _i452 = 0; _i452 < _list451.Count; ++_i452)
                {
                  CellValueSerial _elem453;
                  _elem453 = new CellValueSerial();
                  await _elem453.ReadAsync(iprot, cancellationToken);
                  V.Add(_elem453);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp454 = new TStruct("CCellSerial");
      await oprot.WriteStructBeginAsync(tmp454, cancellationToken);
      var tmp455 = new TField();
      if((K != null) && __isset.@k)
      {
        tmp455.Name = "k";
        tmp455.Type = TType.List;
        tmp455.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp455, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.String, K.Count), cancellationToken);
        foreach (byte[] _iter456 in K)
        {
          await oprot.WriteBinaryAsync(_iter456, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@ts)
      {
        tmp455.Name = "ts";
        tmp455.Type = TType.I64;
        tmp455.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp455, cancellationToken);
        await oprot.WriteI64Async(Ts, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((V != null) && __isset.@v)
      {
        tmp455.Name = "v";
        tmp455.Type = TType.List;
        tmp455.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp455, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.Struct, V.Count), cancellationToken);
        foreach (CellValueSerial _iter457 in V)
        {
          await _iter457.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is CCellSerial other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.@k == other.__isset.@k) && ((!__isset.@k) || (global::System.Object.Equals(K, other.K))))
      && ((__isset.@ts == other.__isset.@ts) && ((!__isset.@ts) || (global::System.Object.Equals(Ts, other.Ts))))
      && ((__isset.@v == other.__isset.@v) && ((!__isset.@v) || (global::System.Object.Equals(V, other.V))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((K != null) && __isset.@k)
      {
        hashcode = (hashcode * 397) + K.GetHashCode();
      }
      if(__isset.@ts)
      {
        hashcode = (hashcode * 397) + Ts.GetHashCode();
      }
      if((V != null) && __isset.@v)
      {
        hashcode = (hashcode * 397) + V.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp458 = new StringBuilder("CCellSerial(");
    int tmp459 = 0;
    if((K != null) && __isset.@k)
    {
      if(0 < tmp459++) { tmp458.Append(", "); }
      tmp458.Append("K: ");
      K.ToString(tmp458);
    }
    if(__isset.@ts)
    {
      if(0 < tmp459++) { tmp458.Append(", "); }
      tmp458.Append("Ts: ");
      Ts.ToString(tmp458);
    }
    if((V != null) && __isset.@v)
    {
      if(0 < tmp459++) { tmp458.Append(", "); }
      tmp458.Append("V: ");
      V.ToString(tmp458);
    }
    tmp458.Append(')');
    return tmp458.ToString();
  }
}

