/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


/// <summary>
/// The Counter column type Fraction Cell for results on Fraction of scan
/// </summary>
public partial class FCellCounter : TBase
{
  private string _c;
  private long _ts;
  private long _v;
  private long _eq;

  /// <summary>
  /// The Column Name
  /// </summary>
  public string C
  {
    get
    {
      return _c;
    }
    set
    {
      __isset.@c = true;
      this._c = value;
    }
  }

  /// <summary>
  /// The Cell Timestamp
  /// </summary>
  public long Ts
  {
    get
    {
      return _ts;
    }
    set
    {
      __isset.@ts = true;
      this._ts = value;
    }
  }

  /// <summary>
  /// The Cell Counter Value
  /// </summary>
  public long V
  {
    get
    {
      return _v;
    }
    set
    {
      __isset.@v = true;
      this._v = value;
    }
  }

  /// <summary>
  /// The Counter EQ since ts
  /// </summary>
  public long Eq
  {
    get
    {
      return _eq;
    }
    set
    {
      __isset.@eq = true;
      this._eq = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool @c;
    public bool @ts;
    public bool @v;
    public bool @eq;
  }

  public FCellCounter()
  {
  }

  public FCellCounter DeepCopy()
  {
    var tmp522 = new FCellCounter();
    if((C != null) && __isset.@c)
    {
      tmp522.C = this.C;
    }
    tmp522.__isset.@c = this.__isset.@c;
    if(__isset.@ts)
    {
      tmp522.Ts = this.Ts;
    }
    tmp522.__isset.@ts = this.__isset.@ts;
    if(__isset.@v)
    {
      tmp522.V = this.V;
    }
    tmp522.__isset.@v = this.__isset.@v;
    if(__isset.@eq)
    {
      tmp522.Eq = this.Eq;
    }
    tmp522.__isset.@eq = this.__isset.@eq;
    return tmp522;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              C = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I64)
            {
              Ts = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.I64)
            {
              V = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.I64)
            {
              Eq = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp523 = new TStruct("FCellCounter");
      await oprot.WriteStructBeginAsync(tmp523, cancellationToken);
      var tmp524 = new TField();
      if((C != null) && __isset.@c)
      {
        tmp524.Name = "c";
        tmp524.Type = TType.String;
        tmp524.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp524, cancellationToken);
        await oprot.WriteStringAsync(C, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@ts)
      {
        tmp524.Name = "ts";
        tmp524.Type = TType.I64;
        tmp524.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp524, cancellationToken);
        await oprot.WriteI64Async(Ts, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@v)
      {
        tmp524.Name = "v";
        tmp524.Type = TType.I64;
        tmp524.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp524, cancellationToken);
        await oprot.WriteI64Async(V, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@eq)
      {
        tmp524.Name = "eq";
        tmp524.Type = TType.I64;
        tmp524.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp524, cancellationToken);
        await oprot.WriteI64Async(Eq, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is FCellCounter other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.@c == other.__isset.@c) && ((!__isset.@c) || (global::System.Object.Equals(C, other.C))))
      && ((__isset.@ts == other.__isset.@ts) && ((!__isset.@ts) || (global::System.Object.Equals(Ts, other.Ts))))
      && ((__isset.@v == other.__isset.@v) && ((!__isset.@v) || (global::System.Object.Equals(V, other.V))))
      && ((__isset.@eq == other.__isset.@eq) && ((!__isset.@eq) || (global::System.Object.Equals(Eq, other.Eq))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((C != null) && __isset.@c)
      {
        hashcode = (hashcode * 397) + C.GetHashCode();
      }
      if(__isset.@ts)
      {
        hashcode = (hashcode * 397) + Ts.GetHashCode();
      }
      if(__isset.@v)
      {
        hashcode = (hashcode * 397) + V.GetHashCode();
      }
      if(__isset.@eq)
      {
        hashcode = (hashcode * 397) + Eq.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp525 = new StringBuilder("FCellCounter(");
    int tmp526 = 0;
    if((C != null) && __isset.@c)
    {
      if(0 < tmp526++) { tmp525.Append(", "); }
      tmp525.Append("C: ");
      C.ToString(tmp525);
    }
    if(__isset.@ts)
    {
      if(0 < tmp526++) { tmp525.Append(", "); }
      tmp525.Append("Ts: ");
      Ts.ToString(tmp525);
    }
    if(__isset.@v)
    {
      if(0 < tmp526++) { tmp525.Append(", "); }
      tmp525.Append("V: ");
      V.ToString(tmp525);
    }
    if(__isset.@eq)
    {
      if(0 < tmp526++) { tmp525.Append(", "); }
      tmp525.Append("Eq: ");
      Eq.ToString(tmp525);
    }
    tmp525.Append(')');
    return tmp525.ToString();
  }
}

