/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


/// <summary>
/// The Timestamp Specifications
/// </summary>
public partial class SpecTimestamp : TBase
{
  private Comp _comp;
  private long _ts;

  /// <summary>
  /// Logical comparator to Apply
  /// 
  /// <seealso cref="global::.Comp"/>
  /// </summary>
  public Comp Comp
  {
    get
    {
      return _comp;
    }
    set
    {
      __isset.@comp = true;
      this._comp = value;
    }
  }

  /// <summary>
  /// The timestamp in nanoseconds to match against the Cell timestamp/version (not the revision)
  /// </summary>
  public long Ts
  {
    get
    {
      return _ts;
    }
    set
    {
      __isset.@ts = true;
      this._ts = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool @comp;
    public bool @ts;
  }

  public SpecTimestamp()
  {
  }

  public SpecTimestamp DeepCopy()
  {
    var tmp154 = new SpecTimestamp();
    if(__isset.@comp)
    {
      tmp154.Comp = this.Comp;
    }
    tmp154.__isset.@comp = this.__isset.@comp;
    if(__isset.@ts)
    {
      tmp154.Ts = this.Ts;
    }
    tmp154.__isset.@ts = this.__isset.@ts;
    return tmp154;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32)
            {
              Comp = (Comp)await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I64)
            {
              Ts = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp155 = new TStruct("SpecTimestamp");
      await oprot.WriteStructBeginAsync(tmp155, cancellationToken);
      var tmp156 = new TField();
      if(__isset.@comp)
      {
        tmp156.Name = "comp";
        tmp156.Type = TType.I32;
        tmp156.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp156, cancellationToken);
        await oprot.WriteI32Async((int)Comp, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@ts)
      {
        tmp156.Name = "ts";
        tmp156.Type = TType.I64;
        tmp156.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp156, cancellationToken);
        await oprot.WriteI64Async(Ts, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is SpecTimestamp other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.@comp == other.__isset.@comp) && ((!__isset.@comp) || (global::System.Object.Equals(Comp, other.Comp))))
      && ((__isset.@ts == other.__isset.@ts) && ((!__isset.@ts) || (global::System.Object.Equals(Ts, other.Ts))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.@comp)
      {
        hashcode = (hashcode * 397) + Comp.GetHashCode();
      }
      if(__isset.@ts)
      {
        hashcode = (hashcode * 397) + Ts.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp157 = new StringBuilder("SpecTimestamp(");
    int tmp158 = 0;
    if(__isset.@comp)
    {
      if(0 < tmp158++) { tmp157.Append(", "); }
      tmp157.Append("Comp: ");
      Comp.ToString(tmp157);
    }
    if(__isset.@ts)
    {
      if(0 < tmp158++) { tmp157.Append(", "); }
      tmp157.Append("Ts: ");
      Ts.ToString(tmp157);
    }
    tmp157.Append(')');
    return tmp157.ToString();
  }
}

