/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

/// <summary>
/// The Scan options Flags Specifications for the SpecFlags 'options' bit
/// </summary>
public enum SpecFlagsOpt
{
  /// <summary>
  /// No Flag Applied
  /// </summary>
  NONE = 0,
  /// <summary>
  /// Cells Limit by Keys
  /// </summary>
  LIMIT_BY_KEYS = 1,
  /// <summary>
  /// Cells Offset by Keys
  /// </summary>
  OFFSET_BY_KEYS = 4,
  /// <summary>
  /// Select Cells Only Keys without Value data
  /// </summary>
  ONLY_KEYS = 8,
  /// <summary>
  /// Select Cells Only with DELETE(cell-flag)
  /// </summary>
  ONLY_DELETES = 10,
}
